import Head from "next/head";
import { Inter } from "next/font/google";
import Sidebar from "@/components/Sidebar/Sidebar";
import Feed from "@/components/Feed/Feed";
import Widgets from "@/components/Widgets/Widgets";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Tweet It Out</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid grid-cols-9 lg:max-w-6xl mx-auto">
        <Sidebar />
        <Feed />
        <Widgets />
      </main>
    </>
  );
}
